# Tutorial Numpy

Bem-vindo ao tutorial de Numpy(!!!...!!)

O Numpy é uma biblioteca que fornece uma estrutura que é usada como base para várias outras bibliotecas como Scipy, matplotlib e pandas. É de grande importância, pois ela permite que as contas sejam feitas de maneira vetorizada, ou seja, mais rápida e eficiente. 

A base estrutural do Numpy são as **arrays**. Elas são parecidas com listas, porém tem tamanho fixo e todos seus elementos são de mesmo tipo.

Para saber mais a fundo, veja o [tutorial do numpy](https://docs.scipy.org/doc/numpy/user/quickstart.html), [introdução básica](https://docs.scipy.org/doc/numpy/user/basics.html) e [documentação de métodos implementados](https://docs.scipy.org/doc/numpy/reference/routines.html).

Ou caso tenha alguma pergunta, sugestão ou apenas quiser nos conhecer, junte-se ao [nosso slack J!QAcademy](https://bit.ly/Jqaslack).

Primeiramente, vamos importar essa biblioteca para nosso notebook, e atribuir um "nick" para ela: **np**.

In [1]:
import numpy as np

## Criação de ndarrays
Na documentação conseguimos ver que o método np.array() possui 6 argumentos, dos quais 5 são opcionais e 1 é obrigatório (object). E a descrição dele é "Create an array.". Veja que cada argumento é descrito na seção "Parameters" com o tipo de entrada que cada argumento e se é opcional e uma descrição do que o argumento influencia na função. Em geral, bibliotecas bem documentadas possuem esse formato de especificação de métodos e funções. Sempre atente para os tipos de objetos que cada argumento requer e o tipo de objeto que sai da função, neste caso '[ndarray](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)' que é o formato da estrutura do numpy.

![Imagem da documentação do numpy.array.](images/array-doc.png)


In [2]:
x = np.array([11,12,13,14,15,16,17,18,19])
x

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

## Tipo de variável das arrays (dtypes)
Abaixo seguem alguns exemplos de como criar arrays no numpy, e também alguns exemplos especificando o tipo das variáveis.

In [3]:
x = np.array ([1,2,3])
x.dtype

dtype('int32')

In [4]:
x = np.array ([1.4,2.2,3.5])
x.dtype

dtype('float64')

In [5]:
x = np.array ([True, False])
x.dtype

dtype('bool')

In [6]:
x = np.array ([1,2,3], dtype=np.float64)
x

array([1., 2., 3.])

In [7]:
x = np.array ([1,0,3], dtype=np.bool)
x

array([ True, False,  True])

## Método [ndarray.shape()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html)
Este método retorna o tamanho de cada dimensão da array.

In [8]:
x = np.array ([[11,12],
               [21,22],
               [31,32],
               [41,42]])
x.shape

(4, 2)

### Criação de arrays a partir do shape
Podemos criar arrays a partir de funções que não necessitam do valor explícito de cada elemento. Neste caso daremos exemplos exemplos de criação a partir do shape, mas [aqui](https://docs.scipy.org/doc/numpy/user/basics.creation.html#intrinsic-numpy-array-creation) temos exemplos de outros tipos de funções intrínsecas que usam outros tipos de inputs.

In [9]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
y = np.zeros((5,5))
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones (y.shape)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Método [np.reshape()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)
Com este método, podemos rearranjar o shape das arrays. Atente que podemos alterar a ordem dos elementos da array final.

In [12]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = x.reshape ((6,2))
y

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
x.reshape ((6,2), order='F')

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

## Modos de indexação
As arrays aceitam três tipos de indexação: por inteiros (parecido com listas), por listas de inteiros e por booleanas.

In [14]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
x [0]

array([1, 2, 3, 4])

In [16]:
x[0,1]

2

In [17]:
x[2,3]

12

In [18]:
x[1, 1:3]

array([6, 7])

In [19]:
x[:, 1]

array([ 2,  6, 10])

### Indexação por listas de inteiros

In [20]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
x[[0,2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [22]:
#"resorting"
x[[0,2,1]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [23]:
# Também conseguimos duplicar linhas
x[[0,1,2,1,2]]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
np.arange(x.shape[0])

array([0, 1, 2])

### Indexação por array de booleanas
Para indexação booleana, **o index precisa ser uma array**!

In [25]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
index = x > 7
index

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [27]:
x[index]

array([ 8,  9, 10, 11, 12])

## Array computations
Aqui vamos mostrar como as arrays se comportam diante de operações básicas.

Note que ao realizar uma operação entre uma array e um número, a operação é feita com todos os elementos da array (broadcasting), ou seja, ao somarmos 2, vamos somar 2 para cada elemento da array.

Se realizarmos uma operação entre duas arrays de mesmo shape, a operação será feita *elementwise*, ou seja, a operação é realizada entre elementos de posições correspondentes.

In [28]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [29]:
x + 2

array([[3, 4],
       [5, 6]])

In [30]:
x * 5

array([[ 5, 10],
       [15, 20]])

In [31]:
x + y

array([[ 6,  8],
       [10, 12]])

In [32]:
x - y

array([[-4, -4],
       [-4, -4]])

In [33]:
## Elementwise multiplication!
x * y

array([[ 5, 12],
       [21, 32]])

In [34]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

### [numpy functions](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html)
Aqui vamos exemplificar algumas funções próprias do numpy.

Note que conseguimos realizar algumas operações (sqrt, sin, ...) para todos os elementos da array, o que não é possível para listas.

In [35]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [36]:
np.sin(x)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [37]:
x = np.array([[1,2],[3,4]])
y = np.array([5,6])
np.dot(x,y)

array([17, 39])

In [38]:
x = np.array([1,2,3,4,5,6,7,8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
x.sum()

36

In [40]:
x.mean()

4.5

In [41]:
np.cumsum(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [42]:
x = np.array([[1,2,3,4,5,6,7,8], [11,12,13,14,15,16,17,18], [21,22,23,24,25,26,27,28]])
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [11, 12, 13, 14, 15, 16, 17, 18],
       [21, 22, 23, 24, 25, 26, 27, 28]])

In [43]:
x.sum(axis=1)

array([ 36, 116, 196])

In [44]:
x.mean(axis=0)

array([11., 12., 13., 14., 15., 16., 17., 18.])

## Broadcasting
Uma das mais importantes propriedades das arrays é a capaciade de broadcasting.

Broadcasting é feito entre duas arrays de [dimensões compatíveis](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html), ou seja, da direita para a esquerda, as dimensões devem ser de mesmo tamanho ou uma delas deve ser igual a 1.

ex:
```
shape 1: 8x1x3x4
shape 2:   6x3x1
result : 8x6x3x4
```

In [45]:
x = np.random.randint(6, size=(100,3))
x

array([[4, 5, 2],
       [3, 3, 5],
       [4, 0, 5],
       [0, 2, 0],
       [0, 3, 0],
       [2, 0, 3],
       [5, 4, 2],
       [4, 1, 1],
       [1, 2, 2],
       [0, 4, 0],
       [5, 4, 4],
       [3, 3, 5],
       [1, 2, 5],
       [1, 1, 5],
       [3, 1, 1],
       [1, 4, 4],
       [4, 3, 4],
       [3, 0, 4],
       [1, 5, 3],
       [4, 3, 1],
       [0, 1, 0],
       [4, 2, 0],
       [5, 0, 5],
       [0, 5, 4],
       [0, 1, 4],
       [4, 5, 2],
       [2, 1, 4],
       [3, 0, 5],
       [5, 3, 0],
       [0, 2, 2],
       [2, 1, 1],
       [1, 2, 2],
       [5, 0, 5],
       [0, 3, 1],
       [1, 3, 0],
       [1, 1, 0],
       [4, 0, 1],
       [1, 1, 2],
       [1, 4, 1],
       [4, 5, 5],
       [1, 1, 0],
       [1, 2, 4],
       [1, 0, 4],
       [3, 5, 3],
       [5, 4, 4],
       [0, 2, 4],
       [3, 1, 3],
       [4, 1, 4],
       [0, 2, 1],
       [0, 4, 3],
       [3, 5, 0],
       [4, 5, 1],
       [0, 3, 2],
       [2, 3, 2],
       [4, 5, 2],
       [3,

In [46]:
x + 100

array([[104, 105, 102],
       [103, 103, 105],
       [104, 100, 105],
       [100, 102, 100],
       [100, 103, 100],
       [102, 100, 103],
       [105, 104, 102],
       [104, 101, 101],
       [101, 102, 102],
       [100, 104, 100],
       [105, 104, 104],
       [103, 103, 105],
       [101, 102, 105],
       [101, 101, 105],
       [103, 101, 101],
       [101, 104, 104],
       [104, 103, 104],
       [103, 100, 104],
       [101, 105, 103],
       [104, 103, 101],
       [100, 101, 100],
       [104, 102, 100],
       [105, 100, 105],
       [100, 105, 104],
       [100, 101, 104],
       [104, 105, 102],
       [102, 101, 104],
       [103, 100, 105],
       [105, 103, 100],
       [100, 102, 102],
       [102, 101, 101],
       [101, 102, 102],
       [105, 100, 105],
       [100, 103, 101],
       [101, 103, 100],
       [101, 101, 100],
       [104, 100, 101],
       [101, 101, 102],
       [101, 104, 101],
       [104, 105, 105],
       [101, 101, 100],
       [101, 102

In [47]:
v = np.array([5,10,5])
print (x.shape)
print (v.shape)
x + v

(100, 3)
(3,)


array([[ 9, 15,  7],
       [ 8, 13, 10],
       [ 9, 10, 10],
       [ 5, 12,  5],
       [ 5, 13,  5],
       [ 7, 10,  8],
       [10, 14,  7],
       [ 9, 11,  6],
       [ 6, 12,  7],
       [ 5, 14,  5],
       [10, 14,  9],
       [ 8, 13, 10],
       [ 6, 12, 10],
       [ 6, 11, 10],
       [ 8, 11,  6],
       [ 6, 14,  9],
       [ 9, 13,  9],
       [ 8, 10,  9],
       [ 6, 15,  8],
       [ 9, 13,  6],
       [ 5, 11,  5],
       [ 9, 12,  5],
       [10, 10, 10],
       [ 5, 15,  9],
       [ 5, 11,  9],
       [ 9, 15,  7],
       [ 7, 11,  9],
       [ 8, 10, 10],
       [10, 13,  5],
       [ 5, 12,  7],
       [ 7, 11,  6],
       [ 6, 12,  7],
       [10, 10, 10],
       [ 5, 13,  6],
       [ 6, 13,  5],
       [ 6, 11,  5],
       [ 9, 10,  6],
       [ 6, 11,  7],
       [ 6, 14,  6],
       [ 9, 15, 10],
       [ 6, 11,  5],
       [ 6, 12,  9],
       [ 6, 10,  9],
       [ 8, 15,  8],
       [10, 14,  9],
       [ 5, 12,  9],
       [ 8, 11,  8],
       [ 9, 1

## [Funções vetorizadas](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html)

Podemos modificar funções para que elas se comportem de acordo com as regras de broadcasting do numpy.

In [48]:
def div_mult (a,b):
    if a > b:
        return a/b
    else:
        return a*b

In [49]:
x = np.random.randint (1000, size=(1000000,1)) + 1
y = np.random.randint (1000, size=(1000000,1)) + 1

In [50]:
vec_div_mult = np.vectorize(div_mult)

In [51]:
vec_div_mult(x,y)

array([[2.43548387e+00],
       [3.21301775e+00],
       [2.93139000e+05],
       ...,
       [5.96480000e+04],
       [4.34910000e+05],
       [1.14360000e+04]])

##### Contribuidores: 
  - Kazu
